"""The tokenizer: SQL text to a stream of tokens.

A hand-written scanner rather than a regex table.  Two reasons: the tricky parts
of SQL lexing (``''`` inside a string, ``--`` versus ``-``, ``<>`` versus ``<``)
are all one-character lookahead decisions that read clearly as code, and a
hand-written scanner can attach an exact source span and a useful error message
to every token.

    "SELECT * FROM users WHERE age >= 18"
       │       │    │      │     │    │  │
       ▼       ▼    ▼      ▼     ▼    ▼  ▼
    KEYWORD  STAR  KEYWORD  IDENT  KEYWORD  IDENT  GTE  INT_LITERAL  EOF
    [0:6]   [7:8]  [9:13]  [14:19] [20:25] [26:29] [30:32] [33:35]

The lexer never raises on the *first* problem it finds and then stops being
useful: it raises :class:`LexError` with the exact offset, so the editor can put
a squiggle in the right place.

Complexity: O(n) in the length of the input, single pass, one character of
lookahead. No backtracking.

How real systems differ
-----------------------
PostgreSQL's lexer is generated by ``flex`` from ``scan.l``, which is faster and
handles a much larger grammar (dollar-quoting, operators the user can define,
unicode escapes). SQLite hand-writes its tokenizer in ``tokenize.c`` for
exactly the reasons above. ChenDB follows SQLite.
"""

from __future__ import annotations

import time
from typing import Final

from engine.diagnostics.events import TokenEvent, TokenizedEvent
from engine.diagnostics.tracer import NULL_TRACER, Tracer
from engine.errors import LexError
from engine.parser.tokens import KEYWORDS, SourceSpan, Token, TokenType

__all__ = ["Lexer", "tokenize"]

#: Single characters that map straight to a token type.
_SIMPLE: Final[dict[str, TokenType]] = {
    "*": TokenType.STAR,
    ",": TokenType.COMMA,
    ";": TokenType.SEMICOLON,
    "(": TokenType.LPAREN,
    ")": TokenType.RPAREN,
    ".": TokenType.DOT,
    "+": TokenType.PLUS,
    "%": TokenType.PERCENT,
    "=": TokenType.EQ,
}

_QUOTE: Final = "'"
_IDENTIFIER_QUOTE: Final = '"'


class Lexer:
    """Scans one SQL string into tokens.

    Single use: construct, call :meth:`tokenize`, discard.
    """

    __slots__ = ("_line", "_line_start", "_pos", "_source", "_tracer")

    def __init__(self, source: str, *, tracer: Tracer | None = None) -> None:
        self._source = source
        self._pos = 0
        self._line = 1
        self._line_start = 0
        self._tracer = tracer if tracer is not None else NULL_TRACER

    # -- position bookkeeping ---------------------------------------------

    @property
    def _column(self) -> int:
        return self._pos - self._line_start + 1

    def _at_end(self) -> bool:
        return self._pos >= len(self._source)

    def _peek(self, offset: int = 0) -> str:
        index = self._pos + offset
        return self._source[index] if index < len(self._source) else ""

    def _advance(self) -> str:
        char = self._source[self._pos]
        self._pos += 1
        if char == "\n":
            self._line += 1
            self._line_start = self._pos
        return char

    def _span_from(self, start: int, line: int, column: int) -> SourceSpan:
        return SourceSpan(start, self._pos, line, column)

    def _fail(self, message: str, start: int, line: int, column: int) -> LexError:
        return LexError(
            message, start=start, end=max(self._pos, start + 1), line=line, column=column
        )

    # -- main loop ---------------------------------------------------------

    def tokenize(self) -> list[Token]:
        """Scan the whole input. The final token is always ``EOF``."""
        started = time.perf_counter_ns()
        tokens: list[Token] = []

        while True:
            self._skip_trivia()
            start, line, column = self._pos, self._line, self._column

            if self._at_end():
                tokens.append(
                    Token(TokenType.EOF, "", SourceSpan(start, start, line, column))
                )
                break

            token = self._scan_token(start, line, column)
            tokens.append(token)
            if self._tracer.verbose:
                self._tracer.emit(
                    TokenEvent(
                        index=len(tokens) - 1,
                        token_type=token.type.value,
                        lexeme=token.lexeme,
                        start=token.span.start,
                        end=token.span.end,
                        keyword=token.keyword.value if token.keyword else None,
                    )
                )

        if self._tracer.operator:
            self._tracer.emit(
                TokenizedEvent(
                    source_length=len(self._source),
                    token_count=len(tokens),
                    duration_ns=time.perf_counter_ns() - started,
                )
            )
        return tokens

    def _scan_token(self, start: int, line: int, column: int) -> Token:
        char = self._peek()

        if char.isalpha() or char == "_":
            return self._scan_word(start, line, column)
        if char.isdigit():
            return self._scan_number(start, line, column)
        if char == _QUOTE:
            return self._scan_string(start, line, column)
        if char == _IDENTIFIER_QUOTE:
            return self._scan_quoted_identifier(start, line, column)
        return self._scan_operator(start, line, column)

    # -- trivia ------------------------------------------------------------

    def _skip_trivia(self) -> None:
        """Consume whitespace and comments until the next real token."""
        while not self._at_end():
            char = self._peek()
            if char.isspace():
                self._advance()
            elif char == "-" and self._peek(1) == "-":
                self._skip_line_comment()
            elif char == "/" and self._peek(1) == "*":
                self._skip_block_comment()
            else:
                return

    def _skip_line_comment(self) -> None:
        while not self._at_end() and self._peek() != "\n":
            self._advance()

    def _skip_block_comment(self) -> None:
        start, line, column = self._pos, self._line, self._column
        self._advance()  # /
        self._advance()  # *
        while True:
            if self._at_end():
                raise self._fail("unterminated block comment", start, line, column)
            if self._peek() == "*" and self._peek(1) == "/":
                self._advance()
                self._advance()
                return
            self._advance()

    # -- words -------------------------------------------------------------

    def _scan_word(self, start: int, line: int, column: int) -> Token:
        """An identifier or a keyword. They are lexically identical."""
        while not self._at_end() and (self._peek().isalnum() or self._peek() == "_"):
            self._advance()
        lexeme = self._source[start : self._pos]
        span = self._span_from(start, line, column)

        keyword = KEYWORDS.get(lexeme.upper())
        if keyword is not None:
            return Token(TokenType.KEYWORD, lexeme, span, keyword=keyword)
        return Token(TokenType.IDENTIFIER, lexeme, span)

    def _scan_quoted_identifier(self, start: int, line: int, column: int) -> Token:
        """``"quoted name"``, lets a column be called ``select`` or ``order``."""
        self._advance()  # opening quote
        parts: list[str] = []
        while True:
            if self._at_end() or self._peek() == "\n":
                raise self._fail("unterminated quoted identifier", start, line, column)
            char = self._advance()
            if char == _IDENTIFIER_QUOTE:
                if self._peek() == _IDENTIFIER_QUOTE:  # "" is an escaped quote
                    parts.append(self._advance())
                    continue
                break
            parts.append(char)

        name = "".join(parts)
        if not name:
            raise self._fail("empty quoted identifier", start, line, column)
        return Token(
            TokenType.IDENTIFIER,
            self._source[start : self._pos],
            self._span_from(start, line, column),
            value=name,
        )

    # -- numbers -----------------------------------------------------------

    def _scan_number(self, start: int, line: int, column: int) -> Token:
        """An integer or a float. ``1.5``, ``1e10`` and ``1.5e-3`` are floats."""
        while not self._at_end() and self._peek().isdigit():
            self._advance()

        is_float = False
        if self._peek() == "." and self._peek(1).isdigit():
            is_float = True
            self._advance()
            while not self._at_end() and self._peek().isdigit():
                self._advance()

        if self._peek() in ("e", "E"):
            exponent_offset = 1
            if self._peek(1) in ("+", "-"):
                exponent_offset = 2
            if self._peek(exponent_offset).isdigit():
                is_float = True
                for _ in range(exponent_offset):
                    self._advance()
                while not self._at_end() and self._peek().isdigit():
                    self._advance()

        lexeme = self._source[start : self._pos]
        if not self._at_end() and (self._peek().isalpha() or self._peek() == "_"):
            # `123abc` is a typo, not a number followed by an identifier.
            while not self._at_end() and (self._peek().isalnum() or self._peek() == "_"):
                self._advance()
            raise self._fail(
                f"invalid number {self._source[start : self._pos]!r}", start, line, column
            )

        span = self._span_from(start, line, column)
        if is_float:
            return Token(TokenType.FLOAT_LITERAL, lexeme, span, value=float(lexeme))
        return Token(TokenType.INT_LITERAL, lexeme, span, value=int(lexeme))

    # -- strings -----------------------------------------------------------

    def _scan_string(self, start: int, line: int, column: int) -> Token:
        """``'text'``, with ``''`` as the escape for a single quote.

        SQL's escape is doubling, not backslashes. ``'it''s'`` is ``it's``.
        Backslash escapes are a MySQL extension and are deliberately not
        supported: they change what a string means depending on a server
        setting, which is a well-known source of injection bugs.
        """
        self._advance()  # opening quote
        parts: list[str] = []
        while True:
            if self._at_end():
                raise self._fail("unterminated string literal", start, line, column)
            char = self._advance()
            if char == _QUOTE:
                if self._peek() == _QUOTE:
                    parts.append(self._advance())
                    continue
                break
            parts.append(char)

        return Token(
            TokenType.STRING_LITERAL,
            self._source[start : self._pos],
            self._span_from(start, line, column),
            value="".join(parts),
        )

    # -- operators ---------------------------------------------------------

    def _scan_operator(self, start: int, line: int, column: int) -> Token:
        char = self._advance()

        if char == "<":
            if self._peek() == "=":
                self._advance()
                return self._operator(TokenType.LTE, start, line, column)
            if self._peek() == ">":  # SQL's standard "not equal"
                self._advance()
                return self._operator(TokenType.NEQ, start, line, column)
            return self._operator(TokenType.LT, start, line, column)

        if char == ">":
            if self._peek() == "=":
                self._advance()
                return self._operator(TokenType.GTE, start, line, column)
            return self._operator(TokenType.GT, start, line, column)

        if char == "!":
            if self._peek() == "=":
                self._advance()
                return self._operator(TokenType.NEQ, start, line, column)
            raise self._fail("expected '=' after '!'", start, line, column)

        if char == "-":
            return self._operator(TokenType.MINUS, start, line, column)
        if char == "/":
            return self._operator(TokenType.SLASH, start, line, column)

        simple = _SIMPLE.get(char)
        if simple is not None:
            return self._operator(simple, start, line, column)

        raise self._fail(f"unexpected character {char!r}", start, line, column)

    def _operator(self, token_type: TokenType, start: int, line: int, column: int) -> Token:
        return Token(
            token_type,
            self._source[start : self._pos],
            self._span_from(start, line, column),
        )


def tokenize(source: str, *, tracer: Tracer | None = None) -> list[Token]:
    """Convenience wrapper: scan ``source`` into tokens."""
    return Lexer(source, tracer=tracer).tokenize()
